### ISSUE TITLE
calibracion con echopype

### ISSUE THREAD

**Issue by emiliom** [Intercoonecta/proy3-acustica#3]
@hvillalo  paso aquí lo que me escribiste por Slack:

> los valores que necesitamos usar en la calibración de los datos son: Temperatura = 26.15; Salinidad = 34.96; gain = 18.36; sa corr = 0.02; EQA = -12.5. Todo esto solo para la frecuencia 38 kHz.

Voy a correr esto en el jupyterhub. Pero primero necesito información adicional sobre los datos. Específicamente:
- waveform_mode: narrow band (continuous wave?) o broadband?
- encode_mode: complex o power?

Podés ver la documentación sobre la función `compute_Sv` [aquí](https://echopype.readthedocs.io/en/stable/api/echopype.calibrate.compute_Sv.html#echopype.calibrate.compute_Sv)

**Comment by hvillalo** [comment]
waveform_mode = "CW"
encode_mode = "complex"

**Comment by emiliom** [comment]
Perfecto, gracias!

**Comment by emiliom** [comment]
Ya tengo todo en orden. Lo que voy a hacer es correrlo yo todo, y pasarles los archivos netcdf a la carpeta `shared`. Luego les paso el cuaderno jupyter tambien.

**Comment by emiliom** [comment]
Listo. He creado una carpeta nueva en la misma carpeta donde están los archivos raw: `shared/proyecto3/calibrado`. Ahí están los archivos netcdf generados por `compute_Sv`. Hoy en unas horas les pongo el notebook en el repositorio del proyecto.

**Comment by hvillalo** [comment]
Gracias Emilio! Lo revisamos

**Comment by emiliom** [comment]
Ya subí el cuaderno jupyter al repositorio. https://github.com/Intercoonecta/proy3-acustica/blob/main/echopype-ek80-conversion-calibracion.ipynb

Entonces, voy a cerrar el issue.
